### ISSUE TITLE
打不开市场界面菜单和当没邮件时无法打开邮件界面！！！

### ISSUE THREAD

**Issue by ASLCH** [liaojinmin/GeekMail-Pro#9]
版本1.12.2 用默认配置时 输入/市场 打不开界面能听到音效

当玩家删完邮件时 就无法打开邮件的界面了

**Comment by ASLCH** [comment]
打不开市场的原理可能也一样吧 上架物品至市场时也无法打开界面

**Comment by ASLCH** [comment]
还有BUG 在背包无空格的时候领取物品邮件 提示一次后无空位子 还是会领取一次 但是背包里没 地上也没 相当于消失了

**Comment by liaojinmin** [comment]
已修复
